os: osx
osx_image: xcode12.4
language: swift
script:
xcodebuild clean build test -project EssentialDeveloperFeed.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
xcodebuild clean build test -project EssentialDeveloperFeed.xcodeproj -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destionation "platform=iOS Simulator,OS=14.4,name=iPhone 8" ONLY_ACTIVE_ARCH=YES
